services:
  base-image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bullseye
    image: b4f-debian:bullseye
  base-image-slim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bullseye-slim
    image: b4f-debian:bullseye-slim
