services:
  base-image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bookworm
    image: b4f-debian:bookworm
  base-image-slim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bookworm-slim
    image: b4f-debian:bookworm-slim
