services:
  base-image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:stretch
    image: b4f-debian:stretch
  base-image-slim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:stretch-slim
    image: b4f-debian:stretch-slim
