services:
  base-image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:trixie
    image: b4f-debian:trixie
  base-image-slim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:trixie-slim
    image: b4f-debian:trixie-slim
